#include "frame.h"

#ifndef FRAME_R_H
#define FRAME_R_H

#define CONTROL_FRAME_SIZE 28
#define MGMT_FRAME_SIZE 28

#define FRAME_FIRST_MAC_OFFT 4
#define FRAME_SECOND_MAC_OFFT 10
#define FRAME_THIRD_MAC_OFFT 16

#define FC_ALL_MASKS FC_TYPE_CONTROL | FC_TYPE_DATA | FC_TYPE_MANAGEMENT | FC_TYPE_RESERVED

#define MORE_LIKELY_MGMT_FRAME_MAP FC_PRESENT | DI_PRESENT | AD1_PRESENT | AD2_PRESENT | AD3_PRESENT | SC_PRESENT | FCS_PRESENT
#define MORE_LIKELY_MGMT_FRAME_SIZE_WITH_NO_DATA 28

#define FC_TYPES_MASK 0b0000000000001100

typedef enum {
    MGMT_TYPE,
    CTRL_TYPE,
    DATA_TYPE,
    RSVD_TYPE
} frame_type_t;


mapper_t* recover(void*);
frame_type_t type_of_raw_frame(void*);


#endif